# Generated by Django 4.1.7 on 2023-02-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(blank=True, default='', max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PnuUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='익명', max_length=32)),
                ('answer', models.CharField(max_length=16)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=128)),
                ('option_yes', models.CharField(max_length=128)),
                ('option_no', models.CharField(max_length=128)),
            ],
        ),
    ]
